### ISSUE TITLE
Doorbell bug?

### ISSUE THREAD

**Issue by micv2** [ki-bo/megasputm#3]
Hello, 
when I ring the doorbell twice at the beginning of the game, I see Ed going down the stairs. The moment Ed opens the door and comes out, the game freezes. Is my file faulty or is it a bug? 

Best regards, 
MiC

**Comment by ki-bo** [comment]
I don't remember any issues in the final version with this scene, but will try to reproduce. It it happening all the time for you? And only if you ring twice?

Have you double-checked that all your lfl files have the MD5 checksums I provided in the ZIP download? That's the first thing we should check.

**Comment by ki-bo** [comment]
Maybe it is just that you are missing one of the files on the disk? All files listed in original_game_files.txt need to be present. There is a list for disk1 and one for disk2 in that file.

**Comment by micv2** [comment]
Hi, 
thanks for the answer. Ringing the doorbell once is enough. When Ed comes, the game freezes. My files are corrupted. I think the problem can be closed. Thanks anyway, great work 👍

**Comment by micv2** [comment]
I need new glasses!

Disc 2 (44.LFT) was missing, I overlooked it..😮

Thanks 👍

**Comment by ki-bo** [comment]
Thanks for reporting back and great it is working now! Enjoy it! btw: this is using the Amiga files but the game runs much better/smoother than on an A500, so you also get an "upgrade" compared with the A500 version by playing it on the MEGA65 :-)

**Comment by ki-bo** [comment]
I already had it running with the German version and there will be an update soon with the needed translated strings of the engine. No worries, will come.
